server:
  port: 8887

qcloud:
  ufile:
    secret-id: AKIDF0WptlNOGvMYZSwhCWbKo575xdFdliR2
    secret-key: YprhHclgOrseDXcVAbmiPL2UklY5MOin
    region: ap-chengdu
    bucket-name: community-1300346570
    path: https://community-1300346570.cos.ap-chengdu.myqcloud.com

github:
  client:
    id: 53cd0606229ddef3e6e0
    secret: 2aeba1bce87bc6495f9e7421f0fe4f2932b9b68c
  redirect:
    uri: http://localhost:8887/callback
  access:
    token:
      uri: https://github.com/login/oauth/access_token
  user:
    uri: https://api.github.com/user

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name:
      url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.murphy.community.mapper
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  # 数据库
  helper-dialect: mysql
  # 判断合理性比如负数和超过最大总数
  reasonable: true
  # 支持方法参数
  support-methods-arguments: true

logging:
  file:
    name: community.log
    path: ./
    max-size: 10MB
    max-history: 7
  level:
    com.murphy.community.mapper: debug
