package com.murphy.community.mapper;

import com.murphy.community.dto.QuestionQueryDTO;
import com.murphy.community.model.Question;

import java.util.List;

public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Feb 07 20:03:08 CST 2020
     */
    int incViewCount(Question record);
    int incCommentCount(Question record);
    List<Question> selectRelated(Question record);
    List<Question> search(QuestionQueryDTO questionQueryDTO);
}