package com.murphy.community.mapper;

import com.murphy.community.model.Question;

public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Feb 07 20:03:08 CST 2020
     */
    int incView(Question record);
}